# Generated by Django 5.0 on 2024-10-15 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75, verbose_name='Title')),
                ('content', models.TextField(max_length=3500, verbose_name='Main content')),
                ('topic', models.CharField(choices=[('spirituality', 'Spirituality'), ('personal', 'Personal')], max_length=75, verbose_name='Topic')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Publication Date')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
            options={
                'ordering': ['-pub_date'],
            },
        ),
    ]
