# Generated by Django 5.0 on 2024-10-15 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_postmodel_pic_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='pic_source',
            field=models.CharField(blank=True, max_length=175, null=True),
        ),
    ]
